### ISSUE TITLE
I want to fly...

### ISSUE THREAD

**Issue by jlevy44** [hshidara/learn_about_dunking#1]
I would love to learn how to dunk but my JV basketball coach had told me that I couldn't jump over a phone book. Now I'm 25 and less athletic. Is there still hope for me?

**Comment by hshidara** [comment]
Lol you opened an issue hahah

**Comment by jlevy44** [comment]
Your repo is really picking up some steam. Mind if I turn this issue into a PR?

**Comment by jlevy44** [comment]
;)
